### ISSUE TITLE
Getting a "SyntaxError: invalid syntax" error

### ISSUE THREAD

**Issue by keepso** [bmscmoreira/TEMPi#1]
Hello there thank you for the script.

I tried the run it on my Raspberry Pi 4 running on Buster and I get the following error:

`File "TEMPi.sh", line 7
    temp=$(</sys/class/thermal/thermal_zone0/temp)
         ^
         SyntaxError: invalid syntax`
         
I just right clicked the folder and click "Open in Terminal" and then run the "chmod +x TEMPi.sh" command.
Tthen I tried to run the "python3 TEMPi.sh" command and then I get this error
![vncviewer_aUYboSpiaR](https://user-images.githubusercontent.com/89862294/161657052-6255bf2d-265a-4dca-a2d3-717aadbdcfb0.png)
.

**Comment by bmscmoreira** [comment]
Hi. Unfortunately I dont have a Pi right now so I can't re-test it. Have you tried it via cron?

**Comment by keepso** [comment]
Thank you for your reply.

I was trying to make it work from the console that is why I was getting the error I guess.

Just writing `* * * * *` this to start of the command line in crontab didn't worked
So I only changed the start of the crontab command line like this:
`*/1 * * * *` and it started to log in every minute. 

Thank you!

**Comment by bmscmoreira** [comment]
> and it started to log in every minute.

Great to know! Actually i got my hands on a brand new Pi4 2 weeks ago and was hoping to check the script soon (especially since I've overclocked it to 2Ghz inside an Argon One case) to monitor the temps. Now I know I'll do it this weekend because it still works ;)

**Comment by keepso** [comment]
> Actually i got my hands on a brand new Pi4

You're very lucky! I wish I can find one with a reasonable price and make it into another Folding@home machine 😅
